language: node_js
node_js:
  - "0.12"

before_script:
  - cd frontend
  - npm install
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - grunt predeploy
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: "cd .."

branches:
  only:
    - master 

deploy:
  provider: openshift
  user: cris.eze.sua@gmail.com
  password: unq/tps
  domain: pdstp
  skip_cleanup: true
  app:
    master: eventss

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always