language: node_js
node_js:
  - "0.12"

script: ls

branches:
  only:
    - master 

before_deploy:
  - cd frontend
  - npm install
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - grunt predeploy
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cd ..
  - git config user.email "cris.eze.sua@gmail.com"
  - git config user.name "Cristian"
  - git add -f -A
  - git commit -m "deploy openshift"
  - git checkout $TRAVIS_BRANCH

deploy:
  provider: openshift
  user: cris.eze.sua@gmail.com
  password: unq/tps
  domain: pdstp
  skip_cleanup: true
  app:
    master: eventss

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always