language: node_js
node_js:
  - "0.12"

script: ls

branches:
  only:
    - master 

after_success:
  - cd frontend
  - npm install
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - grunt predeploy
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cd ..
  - rm -rf frontend
  - ls
  - git config user.email "cris.eze.sua@gmail.com"
  - git config user.name "Cristian"
  - git add -f -A &> /dev/null
  - git checkout $TRAVIS_BRANCH &> /dev/null
  - git commit -m "deploy heroku" &> /dev/null

deploy:
  provider: heroku
  app: arq1-events
  api_key: a1e85a46-0fe8-4829-9137-21f3adaabd4a
  run: 
    - "php artisan migrate:refresh"
  skip_cleanup: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always